=== OscarMaestre/JXMLTool/dtd.dtd
<!ELEMENT empresa (pedido+)>
<!ATTLIST empresa nombre CDATA #REQUIRED>
<!ELEMENT pedido (sucursal,codigoP, direccionEnvio, nombreTrabajador, fechaPedido, observacionesP?, (articulo+))>

<!ELEMENT sucursal (zonaExposicion, zonaGestion?)>
<!ATTLIST sucursal nombreSucursal CDATA #REQUIRED>
<!ELEMENT zonaExposicion (#PCDATA)>
<!ELEMENT zonaGestion (albaran, pago)>
<!ELEMENT albaran (#PCDATA)>
<!ELEMENT pago (#PCDATA)>


<!ELEMENT codigoP (#PCDATA)>
<!ELEMENT direccionEnvio (#PCDATA)>
<!ELEMENT nombreTrabajador (#PCDATA)>

<!ELEMENT fechaPedido (dia?, mes, anio)>
<!ELEMENT dia      (#PCDATA)>
<!ELEMENT mes      (#PCDATA)>
<!ELEMENT anio     (#PCDATA)>

<!ELEMENT observacionesP (urgente | incompleto)>
<!ELEMENT urgente (#PCDATA)>
<!ELEMENT incompleto (#PCDATA)>

<!ELEMENT articulo ((unidades+),precio, observacionesA?)>
<!ATTLIST articulo codArticulo CDATA #REQUIRED>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT observacionesA (#PCDATA)>

=== OscarMaestre/JXMLTool/fichero_resultado_con.dtd.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE empresa SYSTEM "dtd.dtd">
<empresa nombre="DistanzaSA">
<pedido>
	<sucursal nombreSucursal="Cuenca">

		<zonaExposicion>Cuenca </zonaExposicion>
		<zonaGestion>
			<albaran> 33 </albaran>
			<pago> 68 </pago>

		</zonaGestion>

	</sucursal>	
	
	<codigoP>333444BBB</codigoP>

   	<direccionEnvio>Luz 16 Ciudad Real</direccionEnvio>
 
	<nombreTrabajador>Pepito Perales</nombreTrabajador>

	<fechaPedido>
		<dia>9</dia><mes>1</mes><anio>2020</anio>
	</fechaPedido> 

	<observacionesP>
    		<urgente>URGENTE</urgente>
   	 </observacionesP>
  
  	<articulo codArticulo="123ABC">
		<unidades>33</unidades>
		<precio> 29 </precio>
		<observacionesA> Entregar nave A </observacionesA>
    </articulo>

</pedido>
</empresa>
